(lang dune           3.20)
(name                pcpp)
(generate_opam_files true)
(authors             "Dmitry Ponyatov <dponyatov@gmail.com>")
(maintainers         "Dmitry Ponyatov <dponyatov@gmail.com>")
(bug_reports         "dponyatov@gmail.com")
(homepage            "github: https://github.com/ponyatov/pcpp")
(license             "MIT")
(source              (github ponyatov/pcpp))
(package
 (name                pcpp)
 (synopsis            "PcapPlusPlus")
(description "
[PcapPlusPlus](https://pcapplusplus.github.io/) is a multiplatform C++ library
for capturing, parsing and crafting of network packets. It is designed to be
efficient, powerful and easy to use.
")
(allow_empty)
)
